const goldleText = 
"  ▄██████▄   ▄██████▄   ▄█       ████████▄   ▄█          ▄████████  \n" +
"  ███    ███ ███    ███ ███       ███   ▀███ ███         ███    ███ \n" +
"  ███    █▀  ███    ███ ███       ███    ███ ███         ███    █▀  \n" +
" ▄███        ███    ███ ███       ███    ███ ███        ▄███▄▄▄     \n" +
"▀▀███ ████▄  ███    ███ ███       ███    ███ ███       ▀▀███▀▀▀     \n" +
"  ███    ███ ███    ███ ███       ███    ███ ███         ███    █▄  \n" +
"  ███    ███ ███    ███ ███▌    ▄ ███   ▄███ ███▌    ▄   ███    ███ \n" +
"  ████████▀   ▀██████▀  █████▄▄██ ████████▀  █████▄▄██   ██████████ \n" +
"                        ▀                    ▀                      \n";

export const goldleGators = [{"name":"AJ","degree":"International Studies / Journalism","room":"101","country":"Australia"},
    {"name":"Sushrika Chattopadhyay","degree":"Quantum Engineering","room":"103","country":"Singapore"},
    {"name":"Divakar Dessai","degree":"Software Engineering","room":"104","country":"Singapore"},
    {"name":"Tom O'Sullivan","degree":"Quantum Engineering","room":"106","country":"Australia"},
    {"name":"Abe Zakhem","degree":"Media","room":"108","country":"Australia"},
    {"name":"Harshvardhan Chaudhry","degree":"Computer Engineering","room":"109","country":"Australia"},
    {"name":"Owen Pang","degree":"Commerce / Computer Science","room":"110","country":"Australia"},
    {"name":"Kyra Bhatia","degree":"Psychological Science","room":"113","country":"Singapore"},
    {"name":"Abigail Worswick","degree":"Software Engineering","room":"114","country":"Australia"},
    {"name":"Keon Ackerman","degree":"Medical Science","room":"116","country":"Australia"},
    {"name":"Cian Sterling","degree":"Science / Arts","room":"119","country":"Australia"},
    {"name":"James Nassif","degree":"Commerce / Science","room":"120","country":"Australia"},
    {"name":"Ethan Andreazza","degree":"Software Engineering","room":"121","country":"Australia"},
    {"name":"Johnnie Parris","degree":"Mechatronics Engineering","room":"122","country":"New Zealand"},
    {"name":"Mackenzie Goiser","degree":"Software Engineering","room":"125","country":"Australia"},
    {"name":"Chameen Dayajeewa","degree":"Commerce / Information Systems","room":"126","country":"Australia"},
    {"name":"Jess Hunter","degree":"Civil Engineering","room":"127","country":"New Zealand"},
    {"name":"Sophie Friend","degree":"Medicine","room":"128","country":"Australia"},
    {"name":"Jess Fleming","degree":"Media / Arts","room":"129","country":"Australia"},
    {"name":"Spencer Wong","degree":"Engineering","room":"130","country":"New Zealand"},
    {"name":"Isabella Gooch","degree":"Psychological Science","room":"131","country":"Australia"},
    {"name":"Sharavan Kumar","degree":"Software Engineering","room":"203","country":"United Arab Emirates"},
    {"name":"Aidan Hargraves","degree":"Mechatronics Engineering / Computer Science","room":"204","country":"Australia"},
    {"name":"Rosanne Lee","degree":"Design / Media","room":"205","country":"Hong Kong"},
    {"name":"Inika Weber","degree":"Renewable Energy Engineering","room":"209","country":"Australia"},
    {"name":"Adam Csontos","degree":"Electrical Engineering","room":"210","country":"Australia"},
    {"name":"Elize Carniel","degree":"Medicine","room":"212","country":"Australia"},
    {"name":"Jackson Hoey","degree":"Commerce","room":"214","country":"Australia"},
    {"name":"James Kipps","degree":"Criminology & Criminal Justice","room":"215","country":"Australia"},
    {"name":"Remy Luculano","degree":"Media / Arts","room":"216","country":"Australia"},
    {"name":"Emily Loong","degree":"Biotechnology","room":"218","country":"Malaysia"},
    {"name":"Caitlin Blandford","degree":"Law / Arts","room":"219","country":"Australia"},
    {"name":"James Higginson","degree":"Civil Engineering","room":"222","country":"New Zealand"},
    {"name":"Romduol Bice","degree":"N/A","room":"223","country":"Cambodia"},
    {"name":"Henry Darke","degree":"Actuarial Studies / Commerce","room":"225","country":"Australia"},
    {"name":"Ema Uno","degree":"Arts","room":"226","country":"Japan"},
    {"name":"Charlie Makeham","degree":"Engineering / Computer Science","room":"227","country":"Australia"},
    {"name":"Dinara Jayarathna","degree":"Information Systems","room":"228","country":"Australia"},
    {"name":"Ishaan Nandurkar","degree":"Quantum Engineering / Computer Science","room":"230","country":"Australia"},
    {"name":"Keven Maharaj","degree":"Mechanical Engineering","room":"231","country":"Canada"},
    {"name":"Blair Dowling","degree":"N/A","room":"302","country":"Australia"},
    {"name":"Natalie Ong","degree":"Medicine","room":"303","country":"Australia"},
    {"name":"Priyash Shah","degree":"Data Science","room":"307","country":"Indonesia"},
    {"name":"Maya Mathur","degree":"Law / Arts","room":"308","country":"Thailand"},
    {"name":"Bronte Winship","degree":"Arts","room":"309","country":"Australia"},
    {"name":"Chris Harsdorf","degree":"Mechatronics Engineering","room":"310","country":"Australia"},
    {"name":"Esha Tripathi","degree":"Computer Engineering","room":"311","country":"N/A"},
    {"name":"Tash Lai","degree":"Law / Media","room":"313","country":"Australia"},
    {"name":"Leah Grace Gath","degree":"Finance","room":"314","country":"United Kingdom"},
    {"name":"Sattvik Narayan","degree":"Software Engineering","room":"315","country":"India"},
    {"name":"Madeleine Baker","degree":"Psychological Science","room":"316","country":"Australia"},
    {"name":"Carol Zhang","degree":"Actuarial Studies / Commerce","room":"318","country":"Australia"},
    {"name":"Imreet Singh","degree":"Medicine","room":"319","country":"Australia"},
    {"name":"Kaylea Zhong","degree":"Commerce / Design","room":"320","country":"New Zealand"},
    {"name":"Patrick Graham","degree":"Computer Science","room":"321","country":"Australia"},
    {"name":"Juan Puyo","degree":"Software Engineering","room":"323","country":"Peru"},
    {"name":"Miyu Shimamoto","degree":"Arts","room":"324","country":"Japan"},
    {"name":"Amber Chan","degree":"Communications / Journalism","room":"325","country":"Singapore"},
    {"name":"Joel Jose","degree":"Computer Engineering","room":"326","country":"United Arab Emirates"},
    {"name":"Nishan Mahesh","degree":"Economics / Science","room":"328","country":"India"},
    {"name":"Emily Huo","degree":"International Public Health","room":"329","country":"New Zealand"},
    {"name":"Risha Cheerala","degree":"Commerce","room":"402","country":"N/A"},
    {"name":"Ella Robinson","degree":"Law / Arts","room":"403","country":"Australia"},
    {"name":"Louisa Reid","degree":"Media","room":"404","country":"United Kingdom"},
    {"name":"Christopher Henderson","degree":"N/A","room":"405","country":"Australia"},
    {"name":"Justin Soh","degree":"Law / Psychological Science","room":"406","country":"Singapore"},
    {"name":"Eliza O'Connell","degree":"Animation","room":"407","country":"Australia"},
    {"name":"Ryan Khoo","degree":"Data Science","room":"408","country":"Malaysia"},
    {"name":"Alyssa Hua","degree":"International Public Health","room":"409","country":"Australia"},
    {"name":"Andrew Listiohadi","degree":"Civil Engineering","room":"410","country":"Indonesia"},
    {"name":"Laura Elaine","degree":"Law / Arts","room":"411","country":"Australia"},
    {"name":"Annie Ming Kowalik","degree":"Mechatronics Engineering / Biomedical Engineering","room":"412","country":"Australia"},
    {"name":"Chenuka Wijayaratne","degree":"Construction Management","room":"413","country":"Oman"},
    {"name":"Leila Hickman","degree":"Exercise Physiology","room":"415","country":"Australia"},
    {"name":"Kong Teepirach","degree":"Computer Science","room":"416","country":"Thailand"},
    {"name":"Spandan Shreshta","degree":"Software Engineering","room":"417","country":"Nepal"},
    {"name":"Harriet Carroll","degree":"Construction Management","room":"418","country":"Australia"},
    {"name":"Chloe Oh","degree":"Medicine","room":"419","country":"South Korea"},
    {"name":"Max Haug","degree":"Advanced Mathematics / Engineering","room":"420","country":"Australia"},
    {"name":"Matilda Guymerlightbody","degree":"Psychological Science","room":"421","country":"Australia"},
    {"name":"Amelie Robinson","degree":"Advanced Mathematics / Computer Science","room":"422","country":"Australia"},
    {"name":"Will Reeves","degree":"Mining Engineering","room":"423","country":"Australia"},
    {"name":"Ben Williams","degree":"Finance","room":"424","country":"United States"},
    {"name":"Jack Buchanan","degree":"Software Engineering","room":"425","country":"Australia"},
    {"name":"Robert Stuart Campbell","degree":"Commerce","room":"427","country":"Australia"},
    {"name":"Alannah Scalzo","degree":"Arts","room":"428","country":"Australia"},
    {"name":"Ashwini Sivakumar","degree":"Medicine","room":"429","country":"Australia"},
    {"name":"Ryo Yamazaki","degree":"Arts / International Relations","room":"430","country":"Japan"},
    {"name":"Oliver Kurukchi","degree":"Medicine","room":"431","country":"Australia"},
    {"name":"Victoria Smyth-King","degree":"Social Sciences","room":"502","country":"Australia"},
    {"name":"Taehun Kim","degree":"Computer Science","room":"503","country":"South Korea"},
    {"name":"Nicholas Gray","degree":"Aerospace Engineering","room":"504","country":"Australia"},
    {"name":"Jeremy Southwell","degree":"Quantum Engineering / Computer Science","room":"505","country":"Australia"},
    {"name":"James Rajic-Knight","degree":"Finance","room":"506","country":"Singapore"},
    {"name":"Ashleigh Ang","degree":"Psychological Science","room":"507","country":"Singapore"},
    {"name":"Gurbani Rajpal","degree":"Software Engineering / Physics","room":"510","country":"Australia"},
    {"name":"Ellen Watkin","degree":"N/A","room":"511","country":"Australia"},
    {"name":"Justin Cheung","degree":"Law / Science","room":"512","country":"Hong Kong"},
    {"name":"Kyle Wilson","degree":"Finance","room":"513","country":"Australia"},
    {"name":"Marta Zumaquero","degree":"Engineering / Commerce","room":"514","country":"Spain"},
    {"name":"Tarun Sathish","degree":"Engineering / Computer Science","room":"515","country":"New Zealand"},
    {"name":"Nick Guo","degree":"Actuarial Studies / Computer Science","room":"516","country":"Australia"},
    {"name":"Mitchell Ellis","degree":"Arts","room":"518","country":"Australia"},
    {"name":"Timothy Davies","degree":"Media","room":"519","country":"Australia"},
    {"name":"Ashna Kanagarajah","degree":"Commerce","room":"520","country":"Australia"},
    {"name":"Will Coleman","degree":"Medicine","room":"521","country":"Australia"},
    {"name":"Fletcher Schultz","degree":"Mechanical Engineering","room":"522","country":"Australia"},
    {"name":"Isolde Mamo","degree":"Aviation","room":"523","country":"Australia"},
    {"name":"Harry Deacon","degree":"Aerospace Engineering","room":"524","country":"Australia"},
    {"name":"Hamish Wells","degree":"Drama","room":"525","country":"Australia"},
    {"name":"Nitya Somayajula","degree":"Commerce","room":"526","country":"Singapore"},
    {"name":"Saumya Nagar","degree":"Information Systems","room":"527","country":"Australia"},
    {"name":"Tanya Nayar","degree":"Medicine","room":"528","country":"Singapore"},
    {"name":"Abhiram Yanamandra","degree":"Computer Engineering","room":"529","country":"Singapore"},
    {"name":"Devam Jain","degree":"Computer Science","room":"530","country":"Singapore"},
    {"name":"Saoirse Chu","degree":"Arts / Law","room":"531","country":"Australia"}];

export const goldleFacultyMap = {
    "dataType":"Map",
    "value":[
        ["Faculty of Arts, Design and Architecture",["international relations","journalism","media","arts","design","communications","animation","construction management","international relations","social sciences"]],
        ["Faculty of Engineering",["quantum engineering","software engineering","computer engineering","computer science","mechatronics engineering","civil engineering","engineering","renewable energy engineering","electrical engineering","mechanical engineering","biomedical engineering","mining engineering","aerospace engineering"]],
        ["UNSW Business School",["commerce","information systems","actuarial studies","finance","economics"]],
        ["Faculty of Science",["medical science","science","biotechnology","data science","advanced mathematics","psychological science","physics","aviation"]],
        ["Faculty of Medicine and Health",["medicine","international public health","exercise physiology"]],
        ["Faculty of Law and Justice",["criminology & criminal justice","law"]],
        ["National Institude of Dramatic Art",["drama"]]
    ]
};


export default goldleText;